---
- name: configuring apache2
  hosts: all
  tasks:
   - name: configuring apache2 using child playbooks
     include: "{{item}}"
     with_items:
      - install.yml
      - edit_index.html
      - restart.yml
      - check_url_response.yml
...        
